sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2
    - cabal-install-1.24
    - happy
    - alex


before_install:
- export PATH=/opt/ghc/8.0.2/bin:/opt/cabal/1.24/bin:$PATH


install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests


script:
 - cabal configure --enable-tests
 - cabal test